### ISSUE TITLE
making C++ component on OSX

### ISSUE THREAD

**Issue by verdiverdiverdi** [lducas/SubSieve#1]
make will fail on OSX unless Makefile changed to

all:
	clang++ -fPIC -Ofast -mavx2 -funroll-loops -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7  -c SubSieveLib.cpp -o SubSieveLib.o
	clang++ -shared -Ofast -mavx2 -funroll-loops -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 SubSieveLib.o -o SubSieveLib.so

because the depreciated libstdc++ will be used by default even with the most up to date XCode.

**Comment by lducas** [comment]
Thanks for the notice. I have a very specific makefile for my architecture indeed. I will add comments suggesting to adjust the makefile to user specific setups.
